version: "3"
services:
  freetube:
    image: linuxserver/freetube:version-168465262
    container_name: freetube
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/freetube/config:/config
    ports:
      - "3000:3000"
      - "3001:3001"
    restart: unless-stopped

umbrel:
  title: Freetube
  version: "168465262"
  description: >
    FreeTube is a feature-rich and user-friendly YouTube client with a focus on privacy.
  developer: LinuxServer.io
  repository: https://github.com/linuxserver/docker-freetube
  category: media
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/freetube-logo.png
  website: https://github.com/FreeTubeApp/FreeTube
  support: https://github.com/linuxserver/docker-freetube/issues
  volumes:
    - name: config
      mount: /config
      description: Configuration storage
  ports:
    - name: web
      target: 3000
      published: 3000
      description: Web UI
    - name: secondary
      target: 3001
      published: 3001
      description: Secondary port
  env:
    - name: PUID
      description: User ID for file permissions
    - name: PGID
      description: Group ID for file permissions
    - name: TZ
      description: Timezone setting
